// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Protobuf.Enum {

  /// <summary>Holder for reflection information generated from Enum.proto</summary>
  public static partial class EnumReflection {

    #region Descriptor
    /// <summary>File descriptor for Enum.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgpFbnVtLnByb3RvEghQcm90b2NvbCqEAQoORUhlcm9DbGFzc1R5cGUSGQoV",
            "RUhFUk9fQ0xBU1NfVFlQRV9OT05FEAASHQoZRUhFUk9fQ0xBU1NfVFlQRV9H",
            "VUFSRElBThABEhsKF0VIRVJPX0NMQVNTX1RZUEVfV0laQVJEEAISGwoXRUhF",
            "Uk9fQ0xBU1NfVFlQRV9QUklFU1QQAyqdAQoRRUNyZWF0ZUhlcm9SZXN1bHQS",
            "HAoYRUNSRUFURV9IRVJPX1JFU1VMVF9OT05FEAASHwobRUNSRUFURV9IRVJP",
            "X1JFU1VMVF9TVUNDRVNTEAESJAogRUNSRUFURV9IRVJPX1JFU1VMVF9GQUlM",
            "X09WRVJMQVAQAhIjCh9FQ1JFQVRFX0hFUk9fUkVTVUxUX0ZBSUxfTUlOTUFY",
            "EAMqhwEKC0VPYmplY3RUeXBlEhUKEUVPQkpFQ1RfVFlQRV9OT05FEAASFQoR",
            "RU9CSkVDVF9UWVBFX0hFUk8QARIYChRFT0JKRUNUX1RZUEVfTU9OU1RFUhAC",
            "EhoKFkVPQkpFQ1RfVFlQRV9EUk9QX0lURU0QAxIUChBFT0JKRUNUX1RZUEVf",
            "TlBDEAQqkQEKDkVDcmVhdHVyZVN0YXRlEhgKFEVDUkVBVFVSRV9TVEFURV9J",
            "RExFEAASGAoURUNSRUFUVVJFX1NUQVRFX01PVkUQARIZChVFQ1JFQVRVUkVf",
            "U1RBVEVfU0tJTEwQAhIXChNFQ1JFQVRVUkVfU1RBVEVfRElFEAMSFwoTRUNS",
            "RUFUVVJFX1NUQVRFX0hJVBAEKs8BCghFTW92ZURpchISCg5FTU9WRV9ESVJf",
            "Tk9ORRAAEhAKDEVNT1ZFX0RJUl9VUBABEhYKEkVNT1ZFX0RJUl9VUF9SSUdI",
            "VBACEhMKD0VNT1ZFX0RJUl9SSUdIVBADEhgKFEVNT1ZFX0RJUl9SSUdIVF9E",
            "T1dOEAQSEgoORU1PVkVfRElSX0RPV04QBRIXChNFTU9WRV9ESVJfRE9XTl9M",
            "RUZUEAYSEgoORU1PVkVfRElSX0xFRlQQBxIVChFFTU9WRV9ESVJfTEVGVF9V",
            "UBAIKqMBChBFU2tpbGxGYWlsUmVhc29uEhsKF0VTS0lMTF9GQUlMX1JFQVNP",
            "Tl9OT05FEAASGwoXRVNLSUxMX0ZBSUxfUkVBU09OX1NUVU4QARIbChdFU0tJ",
            "TExfRkFJTF9SRUFTT05fRElTVBACEhsKF0VTS0lMTF9GQUlMX1JFQVNPTl9D",
            "T1NUEAMSGwoXRVNLSUxMX0ZBSUxfUkVBU09OX0NPT0wQBCq2AgoJRVN0YXRU",
            "eXBlEhMKD0VTVEFUX1RZUEVfTk9ORRAAEhUKEUVTVEFUX1RZUEVfTUFYX0hQ",
            "EAESFQoRRVNUQVRfVFlQRV9NQVhfTVAQAhIRCg1FU1RBVF9UWVBFX0hQEAMS",
            "EQoNRVNUQVRfVFlQRV9NUBAEEhIKDkVTVEFUX1RZUEVfQVRLEAUSFgoSRVNU",
            "QVRfVFlQRV9ERUZFTkNFEAYSGQoVRVNUQVRfVFlQRV9NT1ZFX1NQRUVEEAcS",
            "FwoTRVNUQVRfVFlQRV9DUklUSUNBTBAIEh4KGkVTVEFUX1RZUEVfQ1JJVElD",
            "QUxfREFNQUdFEAkSIAocRVNUQVRfVFlQRV9TSElFTERfRUZGSUNJRU5DWRAK",
            "Eh4KGkVTVEFUX1RZUEVfSEVBTF9FRkZJQ0lFTkNZEAsqNgoJRU1vdmVUeXBl",
            "EhMKD0VNT1ZFX1RZUEVfTk9ORRAAEhQKEEVNT1ZFX1RZUEVfQ0hBU0UQASpc",
            "Cg1FTW9uc3RlckdyYWRlEhcKE0VNT05TVEVSX0dSQURFX05PTkUQABIZChVF",
            "TU9OU1RFUl9HUkFERV9OT1JNQUwQARIXChNFTU9OU1RFUl9HUkFERV9SQVJF",
            "EAIqRAoNRVRlbGVwb3J0VHlwZRIXChNFVEVMRVBPUlRfVFlQRV9OT05FEAAS",
            "GgoWRVRFTEVQT1JUX1RZUEVfUkVTUEFXThABKmIKCUVJdGVtVHlwZRITCg9F",
            "SVRFTV9UWVBFX05PTkUQABIUChBFSVRFTV9UWVBFX0VRVUlQEAESFgoSRUlU",
            "RU1fVFlQRV9DT05TVU1FEAISEgoORUlURU1fVFlQRV9FVEMQAyqQAgoORUVx",
            "dWlwSXRlbVR5cGUSGQoVRUVRVUlQX0lURU1fVFlQRV9OT05FEAASGwoXRUVR",
            "VUlQX0lURU1fVFlQRV9XRUFQT04QARIbChdFRVFVSVBfSVRFTV9UWVBFX1NI",
            "SUVMRBACEhsKF0VFUVVJUF9JVEVNX1RZUEVfSEVMTUVUEAMSGgoWRUVRVUlQ",
            "X0lURU1fVFlQRV9BUk1PUhAEEhoKFkVFUVVJUF9JVEVNX1RZUEVfQk9PVFMQ",
            "BRIbChdFRVFVSVBfSVRFTV9UWVBFX0dMT1ZFUxAGEhwKGEVFUVVJUF9JVEVN",
            "X1RZUEVfUEVOREFOVBAHEhkKFUVFUVVJUF9JVEVNX1RZUEVfUklORxAIKrsC",
            "CglFU2xvdFR5cGUSEwoPRVNMT1RfVFlQRV9OT05FEAASFQoRRVNMT1RfVFlQ",
            "RV9XRUFQT04QARIVChFFU0xPVF9UWVBFX1NISUVMRBACEhUKEUVTTE9UX1RZ",
            "UEVfSEVMTUVUEAMSFAoQRVNMT1RfVFlQRV9BUk1PUhAEEhQKEEVTTE9UX1RZ",
            "UEVfQk9PVFMQBRIVChFFU0xPVF9UWVBFX0dMT1ZFUxAGEhYKEkVTTE9UX1RZ",
            "UEVfUEVOREFOVBAHEhkKFUVTTE9UX1RZUEVfRklSU1RfUklORxAIEhoKFkVT",
            "TE9UX1RZUEVfU0VDT05EX1JJTkcQCRIUChBFU0xPVF9UWVBFX0VRVUlQEGQS",
            "FwoSRVNMT1RfVFlQRV9DT05TVU1FEMgBEhMKDkVTTE9UX1RZUEVfRVRDEKwC",
            "KnEKEUVQaWNrdXBGYWlsUmVhc29uEhwKGEVQSUNLVVBfRkFJTF9SRUFTT05f",
            "Tk9ORRAAEiAKHEVQSUNLVVBfRkFJTF9SRUFTT05fTk9UX01JTkUQARIcChhF",
            "UElDS1VQX0ZBSUxfUkVBU09OX0ZVTEwQAio+CgxFQWRkSXRlbVR5cGUSFgoS",
            "RUFERF9JVEVNX1RZUEVfTkVXEAASFgoSRUFERF9JVEVNX1RZUEVfT0xEEAEq",
            "PwoLRUl0ZW1TdGF0dXMSFQoRRUlURU1fU1RBVFVTX05PTkUQABIZChVFSVRF",
            "TV9TVEFUVVNfRVFVSVBQRUQQASpeCg9FQ29uc3VtYWJsZVR5cGUSGQoVRUNP",
            "TlNVTUFCTEVfVFlQRV9OT05FEAASFwoTRUNPTlNVTUFCTEVfVFlQRV9IUBAB",
            "EhcKE0VDT05TVU1BQkxFX1RZUEVfTVAQAiqfAQoLRUVmZmVjdFR5cGUSFQoR",
            "RUVGRkVDVF9UWVBFX05PTkUQABIXChNFRUZGRUNUX1RZUEVfREFNQUdFEAES",
            "FQoRRUVGRkVDVF9UWVBFX0hFQUwQAhIYChRFRUZGRUNUX1RZUEVfQUREU1RB",
            "VBADEhcKE0VFRkZFQ1RfVFlQRV9TSElFTEQQBBIWChJFRUZGRUNUX1RZUEVf",
            "QUdHUk8QBSp/ChNFRWZmZWN0RHVyYXRpb25UeXBlEh4KGkVFRkZFQ1RfRFVS",
            "QVRJT05fVFlQRV9OT05FEAASIwofRUVGRkVDVF9EVVJBVElPTl9UWVBFX1RF",
            "TVBPUkFSWRABEiMKH0VFRkZFQ1RfRFVSQVRJT05fVFlQRV9QRVJNQU5FTlQQ",
            "AiqvAQoSRUVmZmVjdFNjYWxpbmdUeXBlEh0KGUVFRkZFQ1RfU0NBTElOR19U",
            "WVBFX05PTkUQABIcChhFRUZGRUNUX1NDQUxJTkdfVFlQRV9BVEsQARIbChdF",
            "RUZGRUNUX1NDQUxJTkdfVFlQRV9IUBACEh8KG0VFRkZFQ1RfU0NBTElOR19U",
            "WVBFX0VOVElUWRADEh4KGkVFRkZFQ1RfU0NBTElOR19UWVBFX01BWEhQEAQq",
            "UwoKRVNraWxsVHlwZRIUChBFU0tJTExfVFlQRV9OT05FEAASFgoSRVNLSUxM",
            "X1RZUEVfQUNUSVZFEAESFwoTRVNLSUxMX1RZUEVfUEFTU0lWRRACKl4KFEVT",
            "a2lsbFByb2plY3RpbGVUeXBlEh8KG0VTS0lMTF9QUk9KRUNUSUxFX1RZUEVf",
            "Tk9ORRAAEiUKIUVTS0lMTF9QUk9KRUNUSUxFX1RZUEVfUFJPSkVDVElMRRAB",
            "KkgKCEVOUENUeXBlEhIKDkVOUENfVFlQRV9OT05FEAASEwoPRU5QQ19UWVBF",
            "X1NUT1JFEAESEwoPRU5QQ19UWVBFX1FVRVNUEAIqqwEKCUVGb250VHlwZRIT",
            "Cg9FRk9OVF9UWVBFX05PTkUQABITCg9FRk9OVF9UWVBFX0hFQUwQARIZChVF",
            "Rk9OVF9UWVBFX05PUk1BTF9ISVQQAhIbChdFRk9OVF9UWVBFX0NSSVRJQ0FM",
            "X0hJVBADEhMKD0VGT05UX1RZUEVfR09MRBAEEhIKDkVGT05UX1RZUEVfRVhQ",
            "EAUSEwoPRUZPTlRfVFlQRV9NSVNTEAYq9gIKDkVTa2lsbFNsb3RUeXBlEhkK",
            "FUVTS0lMTF9TTE9UX1RZUEVfTk9ORRAAEhsKF0VTS0lMTF9TTE9UX1RZUEVf",
            "Tk9STUFMEAESGQoVRVNLSUxMX1NMT1RfVFlQRV9EQVNIEAISHAoYRVNLSUxM",
            "X1NMT1RfVFlQRV9BQ1RJVkUxEAMSHAoYRVNLSUxMX1NMT1RfVFlQRV9BQ1RJ",
            "VkUyEAQSHAoYRVNLSUxMX1NMT1RfVFlQRV9BQ1RJVkUzEAUSHAoYRVNLSUxM",
            "X1NMT1RfVFlQRV9BQ1RJVkU0EAYSHQoZRVNLSUxMX1NMT1RfVFlQRV9QQVNT",
            "SVZFMRAHEh0KGUVTS0lMTF9TTE9UX1RZUEVfUEFTU0lWRTIQCBIdChlFU0tJ",
            "TExfU0xPVF9UWVBFX1BBU1NJVkUzEAkSHQoZRVNLSUxMX1NMT1RfVFlQRV9Q",
            "QVNTSVZFNBAKEh0KGUVTS0lMTF9TTE9UX1RZUEVfUEFTU0lWRTUQCypjCg5F",
            "U2tpbGxBcmVhVHlwZRIZChVFU0tJTExfQVJFQV9UWVBFX05PTkUQABIbChdF",
            "U0tJTExfQVJFQV9UWVBFX1NJTkdMRRABEhkKFUVTS0lMTF9BUkVBX1RZUEVf",
            "QVJFQRACKoEBChVFU2tpbGxVc2FnZVRhcmdldFR5cGUSIQodRVNLSUxMX1VT",
            "QUdFX1RBUkdFVF9UWVBFX1NFTEYQABIhCh1FU0tJTExfVVNBR0VfVEFSR0VU",
            "X1RZUEVfQUxMWRABEiIKHkVTS0lMTF9VU0FHRV9UQVJHRVRfVFlQRV9FTkVN",
            "WRACKoUBChNFU2tpbGxUYXJnZXRpbmdUeXBlEiQKIEVTS0lMTF9UQVJHRVRJ",
            "TkdfVFlQRV9OT05fVEFSR0VUEAASIAocRVNLSUxMX1RBUkdFVElOR19UWVBF",
            "X1RBUkdFVBABEiYKIkVTS0lMTF9UQVJHRVRJTkdfVFlQRV9TTUFSVF9UQVJH",
            "RVQQAipRChFFTW9uc3RlckFnZ3JvVHlwZRIeChpFTU9OU1RFUl9BR0dST19U",
            "WVBFX01BTlVBTBAAEhwKGEVNT05TVEVSX0FHR1JPX1RZUEVfQVVUTxABKkEK",
            "DUVDdXJyZW5jeVR5cGUSFwoTRUNVUlJFTkNZX1RZUEVfTk9ORRAAEhcKE0VD",
            "VVJSRU5DWV9UWVBFX0dPTEQQASo7CglFUm9vbVR5cGUSFgoSRVJPT01fVFlQ",
            "RV9WSUxMQUdFEAASFgoSRVJPT01fVFlQRV9EVU5HRU9OEAEqWAoMRUR1bmdl",
            "b25UeXBlEhYKEkVEVU5HRU9OX1RZUEVfTk9ORRAAEhgKFEVEVU5HRU9OX1RZ",
            "UEVfTk9STUFMEAESFgoSRURVTkdFT05fVFlQRV9CT1NTEAIqtAEKFkVGYWls",
            "UmVhc29uQ3JlYXRlUGFydHkSIgoeRUZBSUxfUkVBU09OX0NSRUFURV9QQVJU",
            "WV9OT05FEAASIwofRUZBSUxfUkVBU09OX0NSRUFURV9QQVJUWV9FWElTVBAB",
            "EiUKIUVGQUlMX1JFQVNPTl9DUkVBVEVfUEFSVFlfVU5LTk9XThACEioKJkVG",
            "QUlMX1JFQVNPTl9DUkVBVEVfUEFSVFlfTk9UX1NFTEVDVEVEEAMqxgEKFEVQ",
            "YXJ0eU1lbWJlclNsb3RUeXBlEiAKHEVQQVJUWV9NRU1CRVJfU0xPVF9UWVBF",
            "X05PTkUQABIhCh1FUEFSVFlfTUVNQkVSX1NMT1RfVFlQRV9GSVJTVBABEiIK",
            "HkVQQVJUWV9NRU1CRVJfU0xPVF9UWVBFX1NFQ09ORBACEiEKHUVQQVJUWV9N",
            "RU1CRVJfU0xPVF9UWVBFX1RISVJEEAMSIgoeRVBBUlRZX01FTUJFUl9TTE9U",
            "X1RZUEVfRk9VUlRIEARCF6oCFEdvb2dsZS5Qcm90b2J1Zi5FbnVtYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Protobuf.Enum.EHeroClassType), typeof(global::Google.Protobuf.Enum.ECreateHeroResult), typeof(global::Google.Protobuf.Enum.EObjectType), typeof(global::Google.Protobuf.Enum.ECreatureState), typeof(global::Google.Protobuf.Enum.EMoveDir), typeof(global::Google.Protobuf.Enum.ESkillFailReason), typeof(global::Google.Protobuf.Enum.EStatType), typeof(global::Google.Protobuf.Enum.EMoveType), typeof(global::Google.Protobuf.Enum.EMonsterGrade), typeof(global::Google.Protobuf.Enum.ETeleportType), typeof(global::Google.Protobuf.Enum.EItemType), typeof(global::Google.Protobuf.Enum.EEquipItemType), typeof(global::Google.Protobuf.Enum.ESlotType), typeof(global::Google.Protobuf.Enum.EPickupFailReason), typeof(global::Google.Protobuf.Enum.EAddItemType), typeof(global::Google.Protobuf.Enum.EItemStatus), typeof(global::Google.Protobuf.Enum.EConsumableType), typeof(global::Google.Protobuf.Enum.EEffectType), typeof(global::Google.Protobuf.Enum.EEffectDurationType), typeof(global::Google.Protobuf.Enum.EEffectScalingType), typeof(global::Google.Protobuf.Enum.ESkillType), typeof(global::Google.Protobuf.Enum.ESkillProjectileType), typeof(global::Google.Protobuf.Enum.ENPCType), typeof(global::Google.Protobuf.Enum.EFontType), typeof(global::Google.Protobuf.Enum.ESkillSlotType), typeof(global::Google.Protobuf.Enum.ESkillAreaType), typeof(global::Google.Protobuf.Enum.ESkillUsageTargetType), typeof(global::Google.Protobuf.Enum.ESkillTargetingType), typeof(global::Google.Protobuf.Enum.EMonsterAggroType), typeof(global::Google.Protobuf.Enum.ECurrencyType), typeof(global::Google.Protobuf.Enum.ERoomType), typeof(global::Google.Protobuf.Enum.EDungeonType), typeof(global::Google.Protobuf.Enum.EFailReasonCreateParty), typeof(global::Google.Protobuf.Enum.EPartyMemberSlotType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EHeroClassType {
    [pbr::OriginalName("EHERO_CLASS_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EHERO_CLASS_TYPE_GUARDIAN")] Guardian = 1,
    [pbr::OriginalName("EHERO_CLASS_TYPE_WIZARD")] Wizard = 2,
    [pbr::OriginalName("EHERO_CLASS_TYPE_PRIEST")] Priest = 3,
  }

  public enum ECreateHeroResult {
    [pbr::OriginalName("ECREATE_HERO_RESULT_NONE")] None = 0,
    [pbr::OriginalName("ECREATE_HERO_RESULT_SUCCESS")] Success = 1,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_OVERLAP")] FailOverlap = 2,
    [pbr::OriginalName("ECREATE_HERO_RESULT_FAIL_MINMAX")] FailMinmax = 3,
  }

  public enum EObjectType {
    [pbr::OriginalName("EOBJECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EOBJECT_TYPE_HERO")] Hero = 1,
    [pbr::OriginalName("EOBJECT_TYPE_MONSTER")] Monster = 2,
    [pbr::OriginalName("EOBJECT_TYPE_DROP_ITEM")] DropItem = 3,
    [pbr::OriginalName("EOBJECT_TYPE_NPC")] Npc = 4,
  }

  public enum ECreatureState {
    [pbr::OriginalName("ECREATURE_STATE_IDLE")] Idle = 0,
    [pbr::OriginalName("ECREATURE_STATE_MOVE")] Move = 1,
    [pbr::OriginalName("ECREATURE_STATE_SKILL")] Skill = 2,
    [pbr::OriginalName("ECREATURE_STATE_DIE")] Die = 3,
    [pbr::OriginalName("ECREATURE_STATE_HIT")] Hit = 4,
  }

  public enum EMoveDir {
    [pbr::OriginalName("EMOVE_DIR_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_DIR_UP")] Up = 1,
    [pbr::OriginalName("EMOVE_DIR_UP_RIGHT")] UpRight = 2,
    [pbr::OriginalName("EMOVE_DIR_RIGHT")] Right = 3,
    [pbr::OriginalName("EMOVE_DIR_RIGHT_DOWN")] RightDown = 4,
    [pbr::OriginalName("EMOVE_DIR_DOWN")] Down = 5,
    [pbr::OriginalName("EMOVE_DIR_DOWN_LEFT")] DownLeft = 6,
    [pbr::OriginalName("EMOVE_DIR_LEFT")] Left = 7,
    [pbr::OriginalName("EMOVE_DIR_LEFT_UP")] LeftUp = 8,
  }

  public enum ESkillFailReason {
    [pbr::OriginalName("ESKILL_FAIL_REASON_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_FAIL_REASON_STUN")] Stun = 1,
    [pbr::OriginalName("ESKILL_FAIL_REASON_DIST")] Dist = 2,
    [pbr::OriginalName("ESKILL_FAIL_REASON_COST")] Cost = 3,
    [pbr::OriginalName("ESKILL_FAIL_REASON_COOL")] Cool = 4,
  }

  public enum EStatType {
    [pbr::OriginalName("ESTAT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESTAT_TYPE_MAX_HP")] MaxHp = 1,
    [pbr::OriginalName("ESTAT_TYPE_MAX_MP")] MaxMp = 2,
    [pbr::OriginalName("ESTAT_TYPE_HP")] Hp = 3,
    [pbr::OriginalName("ESTAT_TYPE_MP")] Mp = 4,
    [pbr::OriginalName("ESTAT_TYPE_ATK")] Atk = 5,
    [pbr::OriginalName("ESTAT_TYPE_DEFENCE")] Defence = 6,
    [pbr::OriginalName("ESTAT_TYPE_MOVE_SPEED")] MoveSpeed = 7,
    [pbr::OriginalName("ESTAT_TYPE_CRITICAL")] Critical = 8,
    [pbr::OriginalName("ESTAT_TYPE_CRITICAL_DAMAGE")] CriticalDamage = 9,
    [pbr::OriginalName("ESTAT_TYPE_SHIELD_EFFICIENCY")] ShieldEfficiency = 10,
    [pbr::OriginalName("ESTAT_TYPE_HEAL_EFFICIENCY")] HealEfficiency = 11,
  }

  public enum EMoveType {
    [pbr::OriginalName("EMOVE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EMOVE_TYPE_CHASE")] Chase = 1,
  }

  public enum EMonsterGrade {
    [pbr::OriginalName("EMONSTER_GRADE_NONE")] None = 0,
    [pbr::OriginalName("EMONSTER_GRADE_NORMAL")] Normal = 1,
    [pbr::OriginalName("EMONSTER_GRADE_RARE")] Rare = 2,
  }

  public enum ETeleportType {
    [pbr::OriginalName("ETELEPORT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ETELEPORT_TYPE_RESPAWN")] Respawn = 1,
  }

  public enum EItemType {
    [pbr::OriginalName("EITEM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EITEM_TYPE_EQUIP")] Equip = 1,
    [pbr::OriginalName("EITEM_TYPE_CONSUME")] Consume = 2,
    [pbr::OriginalName("EITEM_TYPE_ETC")] Etc = 3,
  }

  public enum EEquipItemType {
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_WEAPON")] Weapon = 1,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_SHIELD")] Shield = 2,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_HELMET")] Helmet = 3,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_ARMOR")] Armor = 4,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_BOOTS")] Boots = 5,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_GLOVES")] Gloves = 6,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_PENDANT")] Pendant = 7,
    [pbr::OriginalName("EEQUIP_ITEM_TYPE_RING")] Ring = 8,
  }

  public enum ESlotType {
    [pbr::OriginalName("ESLOT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESLOT_TYPE_WEAPON")] Weapon = 1,
    [pbr::OriginalName("ESLOT_TYPE_SHIELD")] Shield = 2,
    [pbr::OriginalName("ESLOT_TYPE_HELMET")] Helmet = 3,
    [pbr::OriginalName("ESLOT_TYPE_ARMOR")] Armor = 4,
    [pbr::OriginalName("ESLOT_TYPE_BOOTS")] Boots = 5,
    [pbr::OriginalName("ESLOT_TYPE_GLOVES")] Gloves = 6,
    [pbr::OriginalName("ESLOT_TYPE_PENDANT")] Pendant = 7,
    [pbr::OriginalName("ESLOT_TYPE_FIRST_RING")] FirstRing = 8,
    [pbr::OriginalName("ESLOT_TYPE_SECOND_RING")] SecondRing = 9,
    [pbr::OriginalName("ESLOT_TYPE_EQUIP")] Equip = 100,
    [pbr::OriginalName("ESLOT_TYPE_CONSUME")] Consume = 200,
    [pbr::OriginalName("ESLOT_TYPE_ETC")] Etc = 300,
  }

  public enum EPickupFailReason {
    [pbr::OriginalName("EPICKUP_FAIL_REASON_NONE")] None = 0,
    [pbr::OriginalName("EPICKUP_FAIL_REASON_NOT_MINE")] NotMine = 1,
    [pbr::OriginalName("EPICKUP_FAIL_REASON_FULL")] Full = 2,
  }

  public enum EAddItemType {
    [pbr::OriginalName("EADD_ITEM_TYPE_NEW")] New = 0,
    [pbr::OriginalName("EADD_ITEM_TYPE_OLD")] Old = 1,
  }

  public enum EItemStatus {
    [pbr::OriginalName("EITEM_STATUS_NONE")] None = 0,
    [pbr::OriginalName("EITEM_STATUS_EQUIPPED")] Equipped = 1,
  }

  public enum EConsumableType {
    [pbr::OriginalName("ECONSUMABLE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ECONSUMABLE_TYPE_HP")] Hp = 1,
    [pbr::OriginalName("ECONSUMABLE_TYPE_MP")] Mp = 2,
  }

  public enum EEffectType {
    [pbr::OriginalName("EEFFECT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEFFECT_TYPE_DAMAGE")] Damage = 1,
    [pbr::OriginalName("EEFFECT_TYPE_HEAL")] Heal = 2,
    [pbr::OriginalName("EEFFECT_TYPE_ADDSTAT")] Addstat = 3,
    [pbr::OriginalName("EEFFECT_TYPE_SHIELD")] Shield = 4,
    [pbr::OriginalName("EEFFECT_TYPE_AGGRO")] Aggro = 5,
  }

  public enum EEffectDurationType {
    [pbr::OriginalName("EEFFECT_DURATION_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEFFECT_DURATION_TYPE_TEMPORARY")] Temporary = 1,
    [pbr::OriginalName("EEFFECT_DURATION_TYPE_PERMANENT")] Permanent = 2,
  }

  public enum EEffectScalingType {
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_ATK")] Atk = 1,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_HP")] Hp = 2,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_ENTITY")] Entity = 3,
    [pbr::OriginalName("EEFFECT_SCALING_TYPE_MAXHP")] Maxhp = 4,
  }

  public enum ESkillType {
    [pbr::OriginalName("ESKILL_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_TYPE_ACTIVE")] Active = 1,
    [pbr::OriginalName("ESKILL_TYPE_PASSIVE")] Passive = 2,
  }

  public enum ESkillProjectileType {
    [pbr::OriginalName("ESKILL_PROJECTILE_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_PROJECTILE_TYPE_PROJECTILE")] Projectile = 1,
  }

  public enum ENPCType {
    [pbr::OriginalName("ENPC_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ENPC_TYPE_STORE")] Store = 1,
    [pbr::OriginalName("ENPC_TYPE_QUEST")] Quest = 2,
  }

  public enum EFontType {
    [pbr::OriginalName("EFONT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EFONT_TYPE_HEAL")] Heal = 1,
    [pbr::OriginalName("EFONT_TYPE_NORMAL_HIT")] NormalHit = 2,
    [pbr::OriginalName("EFONT_TYPE_CRITICAL_HIT")] CriticalHit = 3,
    [pbr::OriginalName("EFONT_TYPE_GOLD")] Gold = 4,
    [pbr::OriginalName("EFONT_TYPE_EXP")] Exp = 5,
    [pbr::OriginalName("EFONT_TYPE_MISS")] Miss = 6,
  }

  public enum ESkillSlotType {
    [pbr::OriginalName("ESKILL_SLOT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_NORMAL")] Normal = 1,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_DASH")] Dash = 2,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE1")] Active1 = 3,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE2")] Active2 = 4,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE3")] Active3 = 5,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_ACTIVE4")] Active4 = 6,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE1")] Passive1 = 7,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE2")] Passive2 = 8,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE3")] Passive3 = 9,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE4")] Passive4 = 10,
    [pbr::OriginalName("ESKILL_SLOT_TYPE_PASSIVE5")] Passive5 = 11,
  }

  public enum ESkillAreaType {
    [pbr::OriginalName("ESKILL_AREA_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ESKILL_AREA_TYPE_SINGLE")] Single = 1,
    [pbr::OriginalName("ESKILL_AREA_TYPE_AREA")] Area = 2,
  }

  public enum ESkillUsageTargetType {
    [pbr::OriginalName("ESKILL_USAGE_TARGET_TYPE_SELF")] Self = 0,
    [pbr::OriginalName("ESKILL_USAGE_TARGET_TYPE_ALLY")] Ally = 1,
    [pbr::OriginalName("ESKILL_USAGE_TARGET_TYPE_ENEMY")] Enemy = 2,
  }

  public enum ESkillTargetingType {
    [pbr::OriginalName("ESKILL_TARGETING_TYPE_NON_TARGET")] NonTarget = 0,
    [pbr::OriginalName("ESKILL_TARGETING_TYPE_TARGET")] Target = 1,
    [pbr::OriginalName("ESKILL_TARGETING_TYPE_SMART_TARGET")] SmartTarget = 2,
  }

  public enum EMonsterAggroType {
    [pbr::OriginalName("EMONSTER_AGGRO_TYPE_MANUAL")] Manual = 0,
    [pbr::OriginalName("EMONSTER_AGGRO_TYPE_AUTO")] Auto = 1,
  }

  public enum ECurrencyType {
    [pbr::OriginalName("ECURRENCY_TYPE_NONE")] None = 0,
    [pbr::OriginalName("ECURRENCY_TYPE_GOLD")] Gold = 1,
  }

  public enum ERoomType {
    [pbr::OriginalName("EROOM_TYPE_VILLAGE")] Village = 0,
    [pbr::OriginalName("EROOM_TYPE_DUNGEON")] Dungeon = 1,
  }

  public enum EDungeonType {
    [pbr::OriginalName("EDUNGEON_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EDUNGEON_TYPE_NORMAL")] Normal = 1,
    [pbr::OriginalName("EDUNGEON_TYPE_BOSS")] Boss = 2,
  }

  public enum EFailReasonCreateParty {
    [pbr::OriginalName("EFAIL_REASON_CREATE_PARTY_NONE")] None = 0,
    [pbr::OriginalName("EFAIL_REASON_CREATE_PARTY_EXIST")] Exist = 1,
    [pbr::OriginalName("EFAIL_REASON_CREATE_PARTY_UNKNOWN")] Unknown = 2,
    [pbr::OriginalName("EFAIL_REASON_CREATE_PARTY_NOT_SELECTED")] NotSelected = 3,
  }

  public enum EPartyMemberSlotType {
    [pbr::OriginalName("EPARTY_MEMBER_SLOT_TYPE_NONE")] None = 0,
    [pbr::OriginalName("EPARTY_MEMBER_SLOT_TYPE_FIRST")] First = 1,
    [pbr::OriginalName("EPARTY_MEMBER_SLOT_TYPE_SECOND")] Second = 2,
    [pbr::OriginalName("EPARTY_MEMBER_SLOT_TYPE_THIRD")] Third = 3,
    [pbr::OriginalName("EPARTY_MEMBER_SLOT_TYPE_FOURTH")] Fourth = 4,
  }

  #endregion

}

#endregion Designer generated code
